import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { Button, ButtonGroup, Tooltip } from "@mui/material";

export type AdminLanguage = "en" | "uk";
const storageKey = "massage-admin-language";
const uk: Record<string, string> = {
  "Calendar connection": "Підключення календаря", "Google Calendar connected": "Google Calendar підключено", "Could not connect Google Calendar": "Не вдалося підключити Google Calendar", "Google authorization was cancelled": "Авторизацію Google скасовано", "Connection complete. Choose a calendar in Bot Settings.": "Підключення завершено. Виберіть календар у налаштуваннях бота.", "Google is checking your permission and saving the connection.": "Google перевіряє дозвіл і зберігає підключення.", "Returning to Bot Settings in {seconds} seconds.": "Повернення до налаштувань бота за {seconds} с.", "Your calendar connection is protected by your admin account.": "Підключення календаря захищене обліковим записом адміністратора.", "Authorization could not be completed. Start again from Settings.": "Не вдалося завершити авторизацію. Почніть знову в налаштуваннях.",
  "Massage": "Масаж", "AI": "ШІ", "Assistant workspace": "Робочий простір асистента", "Admin navigation": "Навігація адміністратора", "Admin workspace": "Робочий простір адміністратора", "Europe/Kyiv": "Європа/Київ", "Skip to content": "Перейти до вмісту", "Close navigation": "Закрити навігацію", "Open navigation": "Відкрити навігацію", "Workspace": "Робочий простір", "ADMIN CONSOLE": "ПАНЕЛЬ АДМІНІСТРАТОРА", "Massage / AI": "Масаж / ШІ", "Built around your time.": "Створений з урахуванням вашого часу.", "Dashboard": "Огляд", "Human touch. Assisted by AI.": "Людяність із підтримкою ШІ.", "More space for care.": "Більше часу для турботи.", "Less time on admin.": "Менше часу на адміністрування.", "Your calendar, conversations and assistant — brought together in one thoughtful workspace.": "Календар, розмови й асистент — в одному зручному робочому просторі.", "Calendar settings": "Налаштування календаря", "Your daily workspace": "Ваш робочий простір", "Stay in control": "Усе під контролем", "Make it sound like you.": "Налаштуйте його голос.", "Shape your assistant’s voice and give every answer the right context.": "Налаштуйте стиль асистента й додайте потрібний контекст до кожної відповіді.", "Assistant prompt": "Промпт асистента", "Knowledge Base": "База знань", "Welcome to your workspace": "Ласкаво просимо до робочого простору", "A little intelligence.": "Трохи інтелекту.", "A lot more possibility.": "Значно більше можливостей.", "Sign in to manage your bookings, care for your clients and make your assistant your own.": "Увійдіть, щоб керувати записами, дбати про клієнтів і налаштувати асистента.", "Could not sign in. Please try again.": "Не вдалося увійти. Спробуйте ще раз.", "Private workspace · Authorized administrators only": "Приватний простір · Лише для авторизованих адміністраторів",
  "AI workspace": "Робочий простір ШІ", "Private intelligence": "Приватний інтелектуальний простір", "Space to think. Tools to act.": "Місце для роздумів. Інструменти для дій.", "Your ideas.": "Ваші ідеї.", "A little more possibility.": "Ще більше можливостей.", "A private place to think, search Telegram, and draft messages. Access is managed by the owner.": "Приватний простір для роздумів, пошуку в Telegram і підготовки повідомлень. Доступом керує власник.", "Your workspace. Your conversations.": "Ваш простір. Ваші розмови.", "New chat": "Новий чат", "Your conversations": "Ваші розмови", "A fresh start. Your chats will appear here.": "Почнімо. Тут з’являтимуться ваші чати.", "Sign out": "Вийти", "Skip to conversation": "Перейти до розмови", "Chat history": "Історія чату", "Close chat history": "Закрити історію чатів", "Open chat history": "Відкрити історію чатів", "Connected owner’s Telegram account · Reads automatic · Sends require confirmation": "Підключений Telegram власника · Читання автоматичне · Надсилання потребує підтвердження", "Checking access": "Перевірка доступу", "Workspace unavailable. Sign in with the owner account or a verified email listed in stakeholder settings, then retry.": "Робочий простір недоступний. Увійдіть як власник або з підтвердженою адресою зі списку доступу, потім спробуйте ще раз.", "Retry": "Повторити", "Your private thinking space": "Ваш приватний простір для роздумів", "What would you like to work on?": "Над чим попрацюємо?", "Start a new chat to search Telegram, summarize a conversation, or draft a reply.": "Створіть чат, щоб шукати в Telegram, підсумувати розмову або підготувати відповідь.", "Start a conversation": "Почати розмову", "Loading conversation": "Завантаження розмови", "Could not load this chat.": "Не вдалося завантажити цей чат.", "Review before sending": "Перевірте перед надсиланням", "To:": "Кому:", "Reply to message:": "Відповідь на повідомлення:", "Status:": "Статус:", "Expires:": "Спливає:", "Confirm send": "Підтвердити надсилання", "Cancel": "Скасувати", "Delivery is not confirmed. Check Telegram before creating another send.": "Надсилання не підтверджено. Перевірте Telegram, перш ніж створювати інше.", "Message your assistant": "Напишіть асистенту", "Send prompt": "Надіслати запит", "AI can make mistakes. Review recipients and message text before confirming. A new prompt replaces any pending proposal.": "ШІ може помилятися. Перевірте одержувачів і текст перед підтвердженням. Новий запит замінить незавершену пропозицію.",
  "Loading": "Завантаження", "prompt…": "промпту…", "Could not load the": "Не вдалося завантажити", "prompt.": "промпт.", "Changes apply to the next request.": "Зміни застосуються до наступного запиту.", "Could not save the prompt.": "Не вдалося зберегти промпт.", "Could not reset the prompt.": "Не вдалося скинути промпт.", "Save": "Зберегти", "Reset": "Скинути", "System Two writes replies and can book a confirmed appointment in Calendar. System One checks whether the proposed reply sounds automated.": "Система 2 формує відповіді й може створити підтверджений запис у календарі. Система 1 перевіряє, чи звучить запропонована відповідь автоматично.", "Prompt systems": "Системи промптів", "System One": "Система 1", "System Two": "Система 2", "Loading prompt catalog…": "Завантаження списку промптів…", "Could not load prompt catalog.": "Не вдалося завантажити список промптів.", "System One prompts": "Промпти системи 1", "System Two prompts": "Промпти системи 2",
  "Loading bot settings…": "Завантаження налаштувань бота…", "Could not load bot settings.": "Не вдалося завантажити налаштування бота.", "Changes apply to the next incoming message.": "Зміни застосуються до наступного вхідного повідомлення.", "Maximum read delay (seconds)": "Максимальна затримка перед прочитанням (секунди)", "Random delay before reading a Business message: 0–3,540 seconds (up to 59 minutes).": "Випадкова затримка перед прочитанням Business-повідомлення: 0–3 540 секунд (до 59 хвилин).", "Typing delay per symbol (ms)": "Затримка набору на символ (мс)", "Wait per Unicode symbol before sending an OpenAI answer: 0–800 ms.": "Затримка на кожен символ Unicode перед надсиланням відповіді OpenAI: 0–800 мс.", "Telegram testers": "Тестувальники Telegram", "Only these usernames can use the assistant in Business messages or private bot chats. Add up to 20 usernames.": "Лише ці користувачі можуть спілкуватися з асистентом у Business-повідомленнях або приватних чатах із ботом. Можна додати до 20 імен.", "No testers configured.": "Тестувальників не додано.", "Tester username": "Ім’я тестувальника в Telegram", "Enter username with or without @. Usernames are saved lowercase.": "Введіть ім’я з @ або без нього. Імена зберігаються малими літерами.", "Add tester": "Додати тестувальника", "Could not save bot settings.": "Не вдалося зберегти налаштування бота.", "Admin access": "Доступ адміністраторів", "Grant admin panel access to stakeholders by email. They must sign in with a verified email address.": "Надайте зацікавленим особам доступ до панелі через email. Вони мають увійти з підтвердженою адресою.", "Loading stakeholder access…": "Завантаження доступу зацікавлених осіб…", "Could not load stakeholder access.": "Не вдалося завантажити список доступу.", "No stakeholder emails added yet.": "Email-адреси ще не додані.", "Stakeholder email": "Email зацікавленої особи", "Up to 100 verified email addresses.": "До 100 підтверджених email-адрес.", "Add email": "Додати email", "Could not save stakeholder access.": "Не вдалося зберегти список доступу.", "Save stakeholder access": "Зберегти список доступу", "Only the owner can change stakeholder access.": "Змінювати список доступу може лише власник.",
  "Reply to all users": "Відповідати всім користувачам", "When enabled, the assistant replies to eligible messages from everyone. When disabled, only testers below can use it.": "Увімкнено — асистент відповідає на придатні повідомлення всіх користувачів. Вимкнено — лише тестувальникам нижче.", "This list applies when all-users mode is disabled. Add up to 20 usernames.": "Цей список діє, коли режим для всіх вимкнений. Додайте до 20 імен користувачів.",
  "Clear context": "Очистити контекст", "Context cleared.": "Контекст очищено.", "messages removed.": "повідомлень видалено.", "Could not clear context.": "Не вдалося очистити контекст.", "Request": "Запит", "Follow-up:": "Додаткове повідомлення:", "Last human answer:": "Остання відповідь людини:", "Responder delivery:": "Доставка відповідачу:", "Delivery may have succeeded. Check Telegram before releasing request.": "Повідомлення могло надійти. Перевірте Telegram, перш ніж закривати запит.", "Send human reply": "Надіслати відповідь людини", "Release request": "Закрити запит", "Action failed. Refresh request status.": "Дію не виконано. Оновіть стан запиту.", "Human requests": "Запити до людини", "Refresh": "Оновити", "Loading requests…": "Завантаження запитів…", "Could not load human requests.": "Не вдалося завантажити запити до людини.", "No open requests.": "Відкритих запитів немає.", "Conversations": "Розмови", "Clear context removes stored chat messages and pending proposals. The next assistant reply starts fresh; bookings and human requests stay. Previously submitted OpenAI records and owner-only diagnostics remain.": "Очищення контексту видаляє збережені повідомлення чату й незавершені пропозиції. Асистент почне нову розмову; записи й запити до людини залишаться. Раніше передані OpenAI дані та діагностика власника не видаляються.", "Loading conversations…": "Завантаження розмов…", "Could not load conversations.": "Не вдалося завантажити розмови.", "Telegram username:": "Ім’я в Telegram:", "Assistant:": "Асистент:", "Human request:": "Запит до людини:",
  "Debug": "Діагностика", "Checking access…": "Перевірка доступу…", "Debug tools are available only to the designated owner account.": "Інструменти діагностики доступні лише власнику.", "Debug sections": "Розділи діагностики", "System log": "Системний журнал", "Prompt test": "Тест промпту", "Latest 200 records retained globally. Complete sanitized AI request and response bodies load when expanded. Credentials and hidden reasoning are excluded. Older records are deleted automatically.": "Зберігаються останні 200 записів. Повні очищені запити й відповіді ШІ завантажуються при розгортанні. Облікові дані й приховані міркування виключено. Старі записи видаляються автоматично.", "Filter stage, status or trace": "Фільтр за етапом, станом або трасуванням", "Clear": "Очистити", "Loading logs…": "Завантаження журналу…", "Could not load debug logs.": "Не вдалося завантажити журнал діагностики.", "No diagnostic events yet.": "Подій діагностики ще немає.", "Trace:": "Трасування:", "Chat reference:": "Посилання на чат:", "Clear system log?": "Очистити системний журнал?", "Clear all currently retained diagnostic events? Their private request/response payloads will no longer be accessible.": "Очистити всі збережені події діагностики? Їхні приватні дані запитів і відповідей більше не будуть доступні.", "Could not clear debug logs. Please try again.": "Не вдалося очистити журнал. Спробуйте ще раз.", "No legacy payload available.": "Старі дані запиту недоступні.", "Legacy preview": "Попередній перегляд старих даних", "Payload storage unavailable.": "Сховище даних недоступне.", "Loading complete payload…": "Завантаження повних даних…", "Payload unavailable.": "Дані недоступні.", "No response body received.": "Тіло відповіді не отримано.", "ms ·": "мс ·", "HTTP attempts": "Спроби HTTP-запиту", "Conversation:": "Розмова:", "Model:": "Модель:", "Request metadata": "Метадані запиту", "Request body": "Тіло запиту", "Response body": "Тіло відповіді", "One isolated model turn. No tools execute; no bookings, messages, or events are saved.": "Один ізольований запит до моделі. Інструменти не запускаються; записи, повідомлення та події не зберігаються.", "System": "Система", "Uses a sample recent reply, your example as the client message, and an unsent draft. The score measures whether the draft sounds automated; copied text alone is not proof.": "Використовує приклад нещодавньої відповіді, ваше повідомлення як текст клієнта й ненадіслану чернетку. Оцінка показує, чи схожа чернетка на автоматичну відповідь; збіг тексту сам по собі нічого не доводить.", "Example text": "Приклад тексту", "Sample context used.": "Використаний приклад контексту.",
  "Google Calendar connection": "Підключення Google Calendar", "Sign in with the same admin owner account that started this connection.": "Увійдіть у той самий обліковий запис власника, з якого почали підключення.", "Sign in as owner": "Увійти як власник", "Return to Bot Settings": "Повернутися до налаштувань бота", "Google Calendar": "Google Calendar", "Connect Google Calendar to manage appointments and check busy times. Google will ask for permission to view your calendar list and manage events. Existing events remain when disconnected.": "Підключіть Google Calendar для керування записами й перевірки зайнятості. Google попросить доступ до списку календарів і керування подіями. Після відключення наявні події залишаться.", "Loading Calendar connection…": "Завантаження підключення календаря…", "Could not load Calendar connection.": "Не вдалося завантажити підключення календаря.", "Google authorization setup is incomplete. Ask the administrator to configure the OAuth client, callback URL and encryption key.": "Налаштування авторизації Google не завершене. Попросіть адміністратора налаштувати OAuth-клієнт, callback URL і ключ шифрування.", "Using the existing server configuration. Connect here to manage authorization from Settings.": "Використовується наявне серверне налаштування. Підключіться тут, щоб керувати авторизацією.", "Connect Google Calendar": "Підключити Google Calendar", "Authorization is pending. Finish Google consent or start again; the link expires after ten minutes.": "Очікується авторизація. Завершіть підтвердження Google або почніть знову; посилання діє десять хвилин.", "Selected calendar:": "Вибраний календар:", "Last verified:": "Остання перевірка:", "Loading calendars…": "Завантаження календарів…", "Could not load calendars. Check permissions or reconnect.": "Не вдалося завантажити календарі. Перевірте дозволи або підключіться знову.", "No calendars with permission to edit events were found.": "Не знайдено календарів із дозволом на редагування подій.", "Google calendar": "Календар Google", "Calendars that block appointments": "Календарі, зайнятість у яких блокує запис", "Save conflict calendars": "Зберегти календарі зайнятості", "Use selected calendar": "Використати вибраний календар", "Check Calendar connection": "Перевірити підключення календаря", "Disconnect Google Calendar? New appointments and changes to existing appointments will stop; existing events will remain.": "Відключити Google Calendar? Нові записи й зміни наявних записів припиняться; наявні події залишаться.", "Confirm disconnect": "Підтвердити відключення", "Keep connection": "Залишити підключення", "Contacting Google…": "Зв’язок із Google…",
  "Loading human assistance settings…": "Завантаження налаштувань допомоги людини…", "Could not load human assistance settings.": "Не вдалося завантажити налаштування допомоги людини.", "Human assistance": "Допомога людини", "Before each automatic reply, System One checks whether the draft sounds like a bot using the latest 20 messages and the proposed reply. Copied text alone does not imply automation. Scores above threshold or failed checks request human help.": "Перед автоматичною відповіддю Система 1 перевіряє за останніми 20 повідомленнями й чернеткою, чи звучить вона як відповідь бота. Сам збіг тексту не означає автоматизацію. Оцінка вище порога або помилка перевірки передає запит людині.", "Human assistance threshold:": "Поріг передачі людині:", "Example: score 60%, threshold 60% → send; 61% → human assistance. Score 100% always hands off, even at threshold 100%.": "Приклад: оцінка 60%, поріг 60% → надіслати; 61% → передати людині. Оцінка 100% завжди передає запит, навіть за порога 100%.", "Telegram responders": "Відповідачі в Telegram", "Each responder must send /start to this bot before private notifications can arrive.": "Кожен відповідач має надіслати цьому боту /start, щоб отримувати приватні сповіщення.", "No responders configured. Requests needing human help remain in Conversations.": "Відповідачів не налаштовано. Запити, яким потрібна допомога, залишаться в розділі «Розмови».", "Telegram username": "Ім’я користувача в Telegram", "Up to 20 usernames; @ optional.": "До 20 імен; символ @ необов’язковий.", "Add responder": "Додати відповідача", "Could not save human assistance settings.": "Не вдалося зберегти налаштування допомоги людини.", "Human assistance settings saved.": "Налаштування допомоги людини збережено.", "Save human assistance": "Зберегти налаштування допомоги людини",
  "Loading knowledge base…": "Завантаження бази знань…", "Could not load the knowledge base.": "Не вдалося завантажити базу знань.", "Changes apply to the next assistant request.": "Зміни застосуються до наступного запиту асистента.", "Add business facts and guidance here. Keep response rules in Assistant prompt. Current enabled services, descriptions, durations, and prices are appended automatically from the booking catalog; edit them below.": "Додавайте тут факти про бізнес і рекомендації. Правила відповіді зберігайте у промпті асистента. Увімкнені послуги, описи, тривалості й ціни автоматично беруться з каталогу записів; редагуйте їх нижче.", "Additional business knowledge": "Додаткові відомості про бізнес", "Services automatically included": "Послуги додаються автоматично", "Delete": "Видалити", "No enabled services. Add a service to include it in assistant replies and future bookings.": "Немає активних послуг. Додайте послугу, щоб асистент міг пропонувати її та записувати на неї.", "Could not delete service.": "Не вдалося видалити послугу.", "Could not save the knowledge base.": "Не вдалося зберегти базу знань.", "Could not reset the knowledge base.": "Не вдалося скинути базу знань.", "RESET": "СКИНУТИ", "This removes the service from assistant replies and future booking options. Existing appointments remain unchanged.": "Послугу буде вилучено з відповідей асистента й майбутніх варіантів запису. Наявні записи не зміняться.", "Keep service": "Залишити послугу",
  "Could not open service.": "Не вдалося відкрити послугу.", "Service name": "Назва послуги", "Description for assistant": "Опис для асистента", "Duration and price options (": "Варіанти тривалості й ціни (", "Remove": "Прибрати", "Add duration option": "Додати варіант тривалості", "Could not save service.": "Не вдалося зберегти послугу.", "Save service": "Зберегти послугу",
  "Media preview": "Попередній перегляд медіафайлу", "Describe when this file helps answer a client. The description guides the assistant and is not sent as a caption.": "Опишіть, коли цей файл допоможе відповісти клієнту. Опис скеровує асистента й не надсилається як підпис.", "Suitable situation, question or topic": "Відповідна ситуація, запитання чи тема", "Repeat interval (hours)": "Інтервал повторного надсилання (години)", "24 hours prevents repeating this media in the same chat for one day. 0 allows repeats.": "Інтервал 24 години не дасть повторно надіслати цей файл у тому самому чаті протягом доби. 0 дозволяє повтори.", "Available to assistant": "Доступно асистенту", "Media file": "Медіафайл", "JPEG/PNG up to 5 MB. MP4 up to 20 MB.": "JPEG/PNG до 5 МБ. MP4 до 20 МБ.", "Could not save media.": "Не вдалося зберегти медіафайл.", "Photos and videos the assistant can share when relevant to a client.": "Фото й відео, якими асистент може поділитися, коли це доречно.", "Add media": "Додати медіафайл", "Loading media": "Завантаження медіафайлів", "Could not load media.": "Не вдалося завантажити медіафайли.", "No media yet. Add a file and describe when to send it.": "Медіафайлів ще немає. Додайте файл і опишіть, коли його надсилати.", "Repeat interval:": "Інтервал повтору:", "Edit": "Редагувати", "Delete media?": "Видалити медіафайл?", "This removes the file from Media Store. Messages already sent to clients remain in their chats.": "Файл буде видалено зі сховища медіа. Уже надіслані клієнтам повідомлення залишаться в чатах.", "Could not delete media.": "Не вдалося видалити медіафайл.",
  "Imported free slots": "Імпортовані вільні години", "Read-only messages from the connected Telegram account. Automatic refresh runs on incoming messages at most once every five minutes. Manual refresh can run whenever no sync is in progress.": "Повідомлення лише для читання з підключеного облікового запису Telegram. Автоматичне оновлення запускається на вхідних повідомленнях не частіше ніж раз на п’ять хвилин. Ручну синхронізацію можна запускати після завершення поточної.", "Loading imported slots…": "Завантаження імпортованих вільних годин…", "Could not load imported schedule slots.": "Не вдалося завантажити імпортований розклад.", "No imported free slots yet. Select the source chat in Bot Settings, then use Refresh now.": "Вільні години ще не імпортовано. Виберіть чат-джерело в налаштуваннях бота й натисніть «Оновити зараз».", "Calendar busy times": "Зайнятість календаря", "Calendar snapshot needs a successful sync. See the diagnostic above, then use Refresh now to retry.": "Щоб отримати знімок календаря, потрібна успішна синхронізація. Перегляньте діагностику вище й натисніть «Оновити зараз», щоб повторити.", "No Calendar snapshot yet. The next automatic refresh is:": "Знімка календаря ще немає. Наступне автоматичне оновлення:", "Calendar was unavailable during the last sync (": "Календар був недоступний під час останньої синхронізації (", "). Refresh to try again.": "). Оновіть, щоб спробувати ще раз.", "Checked:": "Перевірено:", "Coverage:": "Період:", "(Europe/Kyiv)": "(Європа/Київ)", "Read-only busy periods. Booking availability is checked live.": "Періоди зайнятості лише для читання. Доступність для запису перевіряється наживо.", "No busy periods in the synchronized Calendar range.": "У синхронізованому періоді календаря зайнятих годин немає.",
  "Schedule source": "Джерело розкладу", "Choose a Telegram chat to import. For groups with topics, choose an inner chat or the whole group. Messages remain read-only; changing source clears the previous snapshot.": "Виберіть чат Telegram для імпорту. Для груп із темами виберіть тему або всю групу. Повідомлення доступні лише для читання; зміна джерела очищує попередній знімок.", "Showing the first 1,000 chats. If yours is missing, move it into your recent chats and reload.": "Показано перші 1 000 чатів. Якщо потрібного немає, відкрийте його в Telegram і перезавантажте список.", "Schedule chat": "Чат розкладу", "Find topic by name": "Знайти тему за назвою", "Search topics": "Шукати теми", "Loading topics…": "Завантаження тем…", "Use Search topics to retry.": "Скористайтеся «Шукати теми», щоб повторити.", "More topics available. Search by name to find a missing topic.": "Доступно більше тем. Знайдіть відсутню тему за назвою.", "No matching topics found.": "Відповідних тем не знайдено.", "Schedule topic": "Тема розкладу", "Save schedule source": "Зберегти джерело розкладу", "Source saved. Use Refresh now to import it; transient failures retry automatically.": "Джерело збережено. Натисніть «Оновити зараз», щоб імпортувати; тимчасові помилки повторюються автоматично.", "Could not load sync status.": "Не вдалося завантажити стан синхронізації.",
  "Source chat:": "Чат-джерело:", "Source topic:": "Тема-джерело:", "Last attempt:": "Остання спроба:", "Last synced:": "Остання синхронізація:", "Manual retry uses up to 5 attempts with 10, 20, 30, then 40 second waits.": "Ручний повтор: до 5 спроб із паузами 10, 20, 30 і 40 секунд.",
  "Telegram caption preview appears here.": "Тут з’явиться попередній перегляд підпису Telegram.", "Loading services…": "Завантаження послуг…", "Could not load services.": "Не вдалося завантажити послуги.", "Service details drive booking. Telegram content controls the customer-facing card.": "Дані послуги використовуються для запису. Вміст Telegram визначає картку для клієнта.", "Add service": "Додати послугу", "Could not change service status.": "Не вдалося змінити стан послуги.", "No services yet. Add a service to let the assistant quote real prices and durations.": "Послуг ще немає. Додайте послугу, щоб асистент називав точні ціни й тривалість.", "min ·": "хв ·", "Buffer": "Буфер", "min": "хв", "Booking details": "Дані для запису", "Duration and price options": "Варіанти тривалості й ціни", "Offer different session lengths under this service. Each duration needs its own price; currency and buffer apply to every option.": "Додайте різну тривалість сеансу для цієї послуги. Для кожної тривалості потрібна ціна; валюта й буфер спільні для всіх варіантів.", "×": "×", "Buffer (minutes)": "Буфер (хвилини)", "Currency": "Валюта", "Offer this service in Telegram": "Показувати послугу в Telegram", "Photo": "Фото", "Service photo preview": "Попередній перегляд фото послуги", "No photo attached": "Фото не додано", "Attach photo": "Додати фото", "JPEG, PNG, WebP · max 5 MiB": "JPEG, PNG, WebP · максимум 5 МіБ", "Service photo": "Фото послуги", "Remove photo": "Прибрати фото", "Telegram caption": "Підпис у Telegram", "Select text, then format it. Telegram supports nested formatting and links. Leave blank for an automatic service summary.": "Виділіть текст, а потім відформатуйте його. Telegram підтримує вкладене форматування й посилання. Залиште порожнім для автоматичного опису послуги.", "Preformatted": "Моноширинний текст", "Link URL": "URL посилання", "Add link": "Додати посилання", "Clear formatting": "Очистити форматування", "Inline URL buttons": "Вбудовані URL-кнопки", "Add URL button": "Додати URL-кнопку", "Telegram preview": "Попередній перегляд Telegram", "Telegram service card": "Картка послуги в Telegram", "Cards are sent when the assistant looks up the service catalog.": "Картки надсилаються, коли асистент шукає послуги в каталозі.",
  "Loading project spec…": "Завантаження специфікації проєкту…", "Could not load the project spec. Try refreshing.": "Не вдалося завантажити специфікацію проєкту. Спробуйте оновити сторінку.", "Repository specification packaged with this release.": "Специфікація репозиторію, включена до цього релізу.", "Project spec": "Специфікація проєкту",
  "Loading System One provider…": "Завантаження провайдера системи 1…", "Could not load System One provider.": "Не вдалося завантажити провайдера системи 1.", "Choose the provider for human handoff probability. OpenAI is the default.": "Виберіть провайдера для оцінки ймовірності передачі людині. За замовчуванням використовується OpenAI.", "System One provider": "Провайдер системи 1", "OpenAI": "OpenAI", "TypeSafe AI": "TypeSafe AI", "Changing providers does not restore discarded proposals or retry bookings.": "Зміна провайдера не відновлює відкинуті пропозиції та не повторює записи.", "Saved. The next System One decision will use this provider.": "Збережено. Для наступного рішення системи 1 буде використано цього провайдера.", "Could not save provider. Please try again.": "Не вдалося зберегти провайдера. Спробуйте ще раз.",
  "Telegram account": "Обліковий запис Telegram", "Connect your account for a read-only schedule import. On incoming Telegram messages, the app reads the five newest text messages from the selected schedule chat at most once every five minutes. This is separate from the Business bot; it never sends messages or marks chats read.": "Підключіть обліковий запис для імпорту розкладу в режимі читання. На вхідних повідомленнях застосунок читає п’ять найновіших текстових повідомлень із вибраного чату не частіше ніж раз на п’ять хвилин. Це окремо від Business-бота: повідомлення не надсилаються, чати не позначаються прочитаними.", "Loading Telegram connection…": "Завантаження підключення Telegram…", "Could not load Telegram connection.": "Не вдалося завантажити підключення Telegram.", "Telegram account connection is not configured. Contact the administrator.": "Підключення облікового запису Telegram не налаштовано. Зверніться до адміністратора.", "Telegram phone number": "Номер телефону Telegram", "+380…": "+380…", "I authorize read-only access to the schedule chat's latest five text messages. Refresh runs at most once every five minutes. This app never sends messages or marks chats read. I can revoke the session here or in Telegram Settings → Devices.": "Я дозволяю доступ лише для читання п’яти останніх текстових повідомлень із чату розкладу. Оновлення запускається не частіше ніж раз на п’ять хвилин. Застосунок не надсилає повідомлень і не позначає чати прочитаними. Я можу відкликати доступ тут або в Telegram: Налаштування → Пристрої.", "Send login code": "Надіслати код входу", "Telegram login code": "Код входу в Telegram", "Check Telegram or SMS for the code. Login expires after 10 minutes.": "Перевірте код у Telegram або SMS. Код діє 10 хвилин.", "Verify code": "Підтвердити код", "Telegram account password": "Пароль облікового запису Telegram", "Enter your personal Telegram account password set for two-step verification, not the one-time login code. Used only for this login; never saved.": "Введіть особистий пароль двоетапної перевірки Telegram, а не одноразовий код. Він використовується лише для цього входу й не зберігається.", "Authorize account": "Авторизувати обліковий запис", "Check connection": "Перевірити підключення", "Contacting Telegram…": "Зв’язок із Telegram…",
  "Loading…": "Завантаження…", "Media Store": "Сховище медіа", "Schedule": "Розклад", "Specs": "Специфікація", "Bot settings": "Налаштування бота",
  "/ AI": "/ ШІ", "Overview": "Огляд", "Control panel": "Панель керування", "Diagnostics": "Діагностика", "Inspect assistant activity and test your prompts.": "Переглядайте роботу асистента й перевіряйте промпти.",
  "Signing in…": "Вхід…", "Sign in with Google": "Увійти через Google", "· Expires:": "· Спливає:", "prompt": "промпт", "· Human request:": "· Запит до людини:", "· Chat reference:": "· Посилання на чат:", "· Model:": "· Модель:", "· Status:": "· Стан:", "Prompt": "Промпт", "h": "год", "https://example.com": "https://example.com", "Intelligence": "Інтелект", "Resources": "Ресурси",
  "Your assistant workspace, at a glance.": "Огляд робочого простору асистента.", "Set your working rhythm. Manage availability and exceptions.": "Налаштуйте робочий графік, доступність і винятки.", "Stay close to your clients. Review conversations and human requests.": "Будьте на зв’язку з клієнтами. Переглядайте розмови й запити до людини.", "Fine-tune how your assistant thinks, speaks and plans.": "Налаштуйте стиль спілкування й роботу асистента.", "Give your assistant the business knowledge behind every answer.": "Додайте бізнес-відомості, потрібні асистенту для відповідей.", "Connect your tools and configure assistant behavior.": "Підключайте інструменти й налаштовуйте поведінку асистента.", "A visual library for more helpful client conversations.": "Бібліотека зображень для корисніших розмов із клієнтами.", "Explore the product behavior and requirements behind your workspace.": "Переглядайте поведінку продукту й вимоги до робочого простору.",
  "01 / AVAILABILITY": "01 / ДОСТУПНІСТЬ", "Your time, in sync": "Ваш час — синхронізовано", "Working hours, exceptions and imported slots.": "Робочі години, винятки й імпортовані години.", "02 / CLIENT CARE": "02 / ТУРБОТА ПРО КЛІЄНТІВ", "Keep the conversation going": "Продовжуйте розмову", "Review client conversations and step in when needed.": "Переглядайте розмови з клієнтами й долучайтеся за потреби.", "03 / CONTENT": "03 / МАТЕРІАЛИ", "Show. Connect. Inspire.": "Показуйте. Зближуйте. Надихайте.", "Curate the photos and videos your assistant shares.": "Добирайте фото й відео, якими ділиться асистент.",
  "Private AI chat": "Приватний чат із ШІ", "You": "Ви", "Assistant": "Асистент", "Reply preview": "Попередній перегляд відповіді", "Message preview": "Попередній перегляд повідомлення", "Processing your choice…": "Обробка вибору…", "Working…": "Обробка…",
  "Custom prompt": "Власний промпт", "Default prompt": "Промпт за замовчуванням", "Custom settings": "Власні налаштування", "Default settings": "Налаштування за замовчуванням",
  "none": "немає", "unavailable": "недоступно", "enabled": "увімкнено", "disabled": "вимкнено", "Clearing…": "Очищення…", "Clear log": "Очистити журнал", " (truncated)": " (скорочено)", "isolated": "ізольований", "not applicable": "не застосовується", "unknown": "невідомо", "Running…": "Виконується…", "Run test": "Запустити тест", "Prompt test failed.": "Не вдалося перевірити промпт.", "Requested tools (not executed)": "Запитані інструменти (не запускалися)", "Output": "Результат",
  "Event modification permission granted.": "Дозвіл на зміну подій надано.", "Reconnect required: event modification permission missing. Disconnect, then connect and allow all requested permissions.": "Потрібно підключитися знову: немає дозволу на зміну подій. Відключіться, підключіться знову й надайте всі запитані дозволи.", "Event modification permission unknown. Check connection; reconnect if permission is missing.": "Невідомо, чи є дозвіл на зміну подій. Перевірте підключення й підключіться знову, якщо дозволу немає.", "(primary)": "(основний)", "Cancel Calendar authorization": "Скасувати авторизацію календаря", "Disconnect Google Calendar": "Відключити Google Calendar",
  "Deleting…": "Видалення…", "Delete service": "Видалити послугу", "Edit service": "Редагувати послугу", "Duration (minutes)": "Тривалість (хвилини)", "Price": "Ціна", "Option {number} duration (minutes)": "Варіант {number}: тривалість (хвилини)", "Option {number} price": "Варіант {number}: ціна", "Button {row}.{column} text": "Кнопка {row}.{column}: текст", "Button {row}.{column} URL": "Кнопка {row}.{column}: URL",
  "Edit media": "Редагувати медіафайл", "Replace file": "Замінити файл", "Choose file": "Вибрати файл", "Saving…": "Збереження…", "Video": "Відео", "Enabled": "Увімкнено", "Disabled": "Вимкнено", "No Calendar snapshot yet. Refresh the schedule to load it.": "Знімка календаря ще немає. Оновіть розклад, щоб завантажити його.",
  "Loading chats…": "Завантаження чатів…", "Load Telegram chats": "Завантажити чати Telegram", "Never": "Ніколи", "Next automatic refresh": "Наступне автоматичне оновлення", "Next permitted refresh": "Наступне дозволене оновлення", "Refreshing…": "Оновлення…", "Retry now": "Повторити зараз", "Refresh now": "Оновити зараз",
  "Active": "Активна", "No assistant description.": "Опису для асистента немає.", "Disable": "Вимкнути", "Enable": "Увімкнути", "Button": "Кнопка", "Check the service fields, caption formatting, and button links.": "Перевірте поля послуги, форматування підпису й посилання кнопок.", "TypeSafe AI falls back to OpenAI on provider errors. A valid probability never triggers fallback.": "Якщо провайдер TypeSafe AI повертає помилку, використовується OpenAI. Коректна оцінка ймовірності не запускає резервний варіант.", "OpenAI assesses handoff directly using the configured OpenAI model.": "OpenAI оцінює передачу запиту безпосередньо налаштованою моделлю.", "Save provider": "Зберегти провайдера", "Disconnect Telegram account": "Відключити обліковий запис Telegram", "Cancel login": "Скасувати вхід",
  "Navigation menu": "Меню навігації", "Interface language": "Мова інтерфейсу", "Sign-in failed. Please try again.": "Не вдалося увійти. Спробуйте ще раз.", "Finishing Google authorization…": "Завершення авторизації Google…", "Authorization details are missing. Start again from Bot Settings.": "Даних авторизації бракує. Почніть знову з налаштувань бота.", "Google account connected. Return to Settings and select the calendar to use.": "Обліковий запис Google підключено. Поверніться до налаштувань і виберіть календар.", "Google authorization was cancelled. You can try again from Settings.": "Авторизацію Google скасовано. Спробуйте ще раз у налаштуваннях.", "Authorization failed. Start again from Settings.": "Не вдалося авторизуватися. Почніть знову в налаштуваннях.",
  "Custom knowledge base": "Власна база знань", "Default knowledge base": "База знань за замовчуванням", "Add": "Додати", "· Coverage:": "· Період:", " (primary)": " (основний)",
  "Loading {label} prompt…": "Завантаження промпту «{label}»…", "Could not load {label} prompt.": "Не вдалося завантажити промпт «{label}».", "{label} instructions": "Інструкції: {label}", "characters": "символів", "Client": "Клієнт", "chat": "чат", "Client chat": "Чат клієнта", "Probability": "Ймовірність", "Reply to request {id}": "Відповідь на запит {id}", "Delete {name}": "Видалити: {name}", "Edit {name}": "Редагувати: {name}", "Remove option {number}": "Прибрати варіант {number}",
  "Telegram message": "Повідомлення Telegram", "group with topics": "група з темами", "topic": "тема", "seconds remaining": "сек. залишилося", "{action} {name}": "{action}: {name}", "service": "послугу", "Used by assistant when explaining this service.": "Використовується асистентом для пояснення послуги.", "photo caption max 1,024": "максимум 1 024 символи для підпису фото", "Remove button {row}.{column}": "Прибрати кнопку {row}.{column}",
  "Switch to day theme": "Увімкнути світлу тему", "Switch to night theme": "Увімкнути темну тему",
  "Handoff": "Передача людині", "Estimates whether the outgoing reply sounds automated, using the latest 20 messages and allowing copied text.": "Оцінює, чи звучить відповідь автоматично, з урахуванням останніх 20 повідомлень і можливого копіювання тексту.", "Writes client replies and can create a Calendar booking after explicit confirmation.": "Формує відповіді клієнтам і створює запис у календарі після явного підтвердження.",
  "open": "відкрито", "answered": "отримано відповідь", "released": "обробку відновлено", "uncertain": "потрібна перевірка", "sending": "надсилається", "sent": "надіслано", "failed": "помилка", "pending": "очікує", "cancelled": "скасовано", "connected": "підключено", "not connected": "не підключено", "disconnected": "відключено", "code": "код", "password": "пароль", "idle": "очікує оновлення", "syncing": "синхронізується", "success": "успішно",
  "knowledge_gap": "бракує бізнес-відомостей", "jev_unavailable": "послуга недоступна", "operation_error": "помилка операції", "bot_detectability": "відповідь схожа на автоматичну", "probability_unavailable": "не вдалося оцінити відповідь", "handoff_probability": "потрібна перевірка відповіді",
  "source_not_found": "чат-джерело або тема не знайдені", "account_busy": "обліковий запис зайнятий", "connection_failed": "помилка з’єднання", "timeout": "час очікування вичерпано", "error": "помилка", "warn": "попередження", "info": "інформація", "provider_request": "запит до провайдера", "received": "повідомлення отримано", "ignored": "повідомлення пропущено", "human_paused": "обробку передано людині", "jev_decision": "рішення системи 1", "assistant_started": "асистент почав відповідь", "tool_called": "виклик інструмента", "booking_context": "контекст запису", "booking_result": "результат запису", "proposal_created": "пропозицію створено", "confirmation_result": "результат підтвердження", "handoff": "передача людині", "reply_sent": "відповідь надіслано", "reply_failed": "не вдалося надіслати відповідь",
  "Choose a JPEG, PNG or MP4 file.": "Виберіть файл JPEG, PNG або MP4.", "Choose a nonempty file up to 5 MB.": "Виберіть непорожній файл розміром до 5 МБ.", "Choose a nonempty file up to 20 MB.": "Виберіть непорожній файл розміром до 20 МБ.", "Check the description, repeat interval and file.": "Перевірте опис, інтервал повторного надсилання й файл.",
  "Saved. Changes apply to the next request.": "Збережено. Зміни застосуються до наступного запиту.", "Reset to the default prompt.": "Промпт за замовчуванням відновлено.", "Saved. Changes apply to the next assistant request.": "Збережено. Зміни застосуються до наступного запиту асистента.", "Reset to the default knowledge base.": "Базу знань за замовчуванням відновлено.", "Service catalog item saved. Changes apply to the next assistant request.": "Послугу збережено. Зміни застосуються до наступного запиту асистента.", "Service deleted from the catalog.": "Послугу видалено з каталогу.", "Service saved.": "Послугу збережено.", "Saved. Changes apply to the next incoming message.": "Збережено. Зміни застосуються до наступного вхідного повідомлення.", "Stakeholder access saved.": "Доступ зацікавлених осіб збережено.",
  "Expected refresh token expiration:": "Очікувана дата завершення дії refresh token:",
  "Calendar selected. New appointments will be created here.": "Календар вибрано. Нові записи створюватимуться тут.", "Conflict calendars saved.": "Календарі зайнятості збережено.", "Google Calendar connection verified.": "Підключення Google Calendar перевірено.", "Google Calendar disconnected.": "Google Calendar відключено.", "Telegram connection verified.": "Підключення Telegram перевірено.", "Telegram account connected.": "Обліковий запис Telegram підключено.", "Telegram account disconnected.": "Обліковий запис Telegram відключено.", "Telegram request failed.": "Не вдалося виконати запит Telegram.", "Sign-out failed. Please try again.": "Не вдалося вийти. Спробуйте ще раз.",
  "Enter a valid Telegram username.": "Введіть коректне ім’я користувача Telegram.", "Enter a valid, unique email address.": "Введіть коректну унікальну email-адресу.", "Invalid username.": "Некоректне ім’я користувача.", "Select caption text first.": "Спершу виділіть текст підпису.", "Invalid formatting selection.": "Вибрано некоректний фрагмент форматування.", "Use a JPEG, PNG, or WebP image.": "Виберіть зображення JPEG, PNG або WebP.", "Image must be 5 MiB or smaller.": "Зображення має бути розміром до 5 МіБ.", "Could not preview the selected image.": "Не вдалося переглянути вибране зображення.", "Service is no longer available. Reload the page.": "Послуга більше недоступна. Перезавантажте сторінку.", "Invalid service details.": "Некоректні дані послуги.",

  "Waiting for a refresh.": "Очікується оновлення.", "Reading the schedule chat…": "Читання чату розкладу…", "Last refresh succeeded.": "Останнє оновлення успішне.", "Source chat was not found, its topic is unavailable, or its name is ambiguous. Select the source in Bot Settings.": "Чат-джерело не знайдено, його тема недоступна або назва неоднозначна. Виберіть джерело в налаштуваннях бота.", "Telegram is disconnected or not configured. Check the account in Bot Settings.": "Telegram відключений або не налаштований. Перевірте обліковий запис у налаштуваннях бота.", "Telegram account is busy with another request. Retry now to start manual retries.": "Обліковий запис Telegram зайнятий іншим запитом. Натисніть «Повторити зараз», щоб запустити повторні спроби.", "Could not read Telegram. Check the connection and retry now.": "Не вдалося прочитати Telegram. Перевірте з’єднання й повторіть зараз.", "Telegram did not finish in time. Retry now to start manual retries.": "Telegram не відповів вчасно. Натисніть «Повторити зараз», щоб запустити повторні спроби.",
  "The file is required.": "Потрібно вибрати файл.", "AD": "АД",
  "OPENAI BALANCE": "БАЛАНС OPENAI", "Loading OpenAI balance…": "Завантаження балансу OpenAI…", "OpenAI balance is unavailable. Try again later.": "Баланс OpenAI недоступний. Спробуйте пізніше.", "Estimated remaining balance": "Орієнтовний залишок", "Total credits": "Усього кредитів", "Used": "Використано", "Set OPENAI_TOTAL_CREDITS on the server to calculate the estimate.": "Задайте OPENAI_TOTAL_CREDITS на сервері, щоб обчислити залишок.",
  "Edit current balance": "Змінити поточний баланс",
  "Current balance (USD)": "Поточний баланс (USD)",
  "Saving sets this as current balance and starts counting costs from now.": "Після збереження ця сума стане поточним балансом, а витрати рахуватимуться від цього часу.",
  "Save a current balance to start the estimate.": "Збережіть поточний баланс, щоб почати розрахунок.",
  "Could not save OpenAI balance.": "Не вдалося зберегти баланс OpenAI."
};

type LocaleContextValue = { language: AdminLanguage; setLanguage: (language: AdminLanguage) => void; t: (key: string, values?: Record<string, string | number>) => string };
const LocaleContext = createContext<LocaleContextValue | null>(null);

function savedLanguage(): AdminLanguage {
  try { return localStorage.getItem(storageKey) === "uk" ? "uk" : "en"; } catch { return "en"; }
}

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AdminLanguage>(savedLanguage);
  const setLanguage = (next: AdminLanguage) => {
    setLanguageState(next);
    try { localStorage.setItem(storageKey, next); } catch { /* The selection remains active until reload. */ }
  };
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo<LocaleContextValue>(() => ({
    language,
    setLanguage,
    t: (key, values) => {
      const template = language === "uk" ? uk[key] ?? key : key;
      return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values?.[name] ?? `{${name}}`));
    },
  }), [language]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useI18n() {
  const context = useContext(LocaleContext);
  if (!context) throw new Error("useI18n must be used inside LocaleProvider");
  return context;
}

export function LanguageToggle() {
  const { language, setLanguage } = useI18n();
  const title = language === "uk" ? "Мова інтерфейсу" : "Interface language";
  return (
    <Tooltip title={title}>
      <ButtonGroup size="small" variant="outlined" aria-label={title}>
        <Button aria-pressed={language === "en"} onClick={() => setLanguage("en")} sx={{ minWidth: 38, px: 1, color: "text.primary", borderColor: "divider", ...(language === "en" ? { bgcolor: "action.selected" } : {}) }}>EN</Button>
        <Button aria-pressed={language === "uk"} onClick={() => setLanguage("uk")} sx={{ minWidth: 38, px: 1, color: "text.primary", borderColor: "divider", ...(language === "uk" ? { bgcolor: "action.selected" } : {}) }}>UA</Button>
      </ButtonGroup>
    </Tooltip>
  );
}
