import { CssBaseline, AppBar, Box, Button, Container, Toolbar, Typography } from '@mui/material'; import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'; import { BrowserRouter, Navigate, NavLink, Route, Routes } from 'react-router-dom'; import { onAuthStateChanged, type User } from 'firebase/auth'; import { useEffect, useState } from 'react'; import { createRoot } from 'react-dom/client';
import { adminApi } from './api.js'; import { auth, signIn } from './auth.js';
const queryClient = new QueryClient();
const Loading = () => <Typography>Loading…</Typography>;
const Login = () => <Container sx={{ mt: 10 }}><Typography variant="h4">Admin login</Typography><Button sx={{ mt: 2 }} variant="contained" onClick={() => void signIn()}>Sign in with Google</Button></Container>;
const Bookings = () => { const query = useQuery({ queryKey: ['bookings'], queryFn: adminApi.bookings }); return <Page title="Bookings">{query.isPending ? <Loading /> : <pre>{JSON.stringify(query.data, null, 2)}</pre>}</Page>; };
const Services = () => { const query = useQuery({ queryKey: ['services'], queryFn: adminApi.services }); return <Page title="Services">{query.isPending ? <Loading /> : <pre>{JSON.stringify(query.data, null, 2)}</pre>}</Page>; };
const Conversations = () => { const query = useQuery({ queryKey: ['conversations'], queryFn: adminApi.conversations }); return <Page title="Conversations">{query.isPending ? <Loading /> : <pre>{JSON.stringify(query.data, null, 2)}</pre>}</Page>; };
const Dashboard = () => <Page title="Dashboard"><Typography>Manage bookings, services, schedule, and assistant automation.</Typography></Page>;
const Schedule = () => <Page title="Schedule"><Typography>Weekly hours and exceptions are managed through the protected API.</Typography></Page>;
const Page = ({ title, children }: { title: string; children: React.ReactNode }) => <Container sx={{ mt: 3 }}><Typography variant="h4" gutterBottom>{title}</Typography>{children}</Container>;
const Protected = ({ user }: { user: User | null }) => user ? <><AppBar position="static"><Toolbar><Typography sx={{ flexGrow: 1 }}>Massage assistant</Typography>{['dashboard', 'bookings', 'services', 'schedule', 'conversations'].map((route) => <Button color="inherit" key={route} component={NavLink} to={`/${route}`}>{route}</Button>)}</Toolbar></AppBar><Routes><Route path="/dashboard" element={<Dashboard />} /><Route path="/bookings" element={<Bookings />} /><Route path="/services" element={<Services />} /><Route path="/schedule" element={<Schedule />} /><Route path="/conversations" element={<Conversations />} /><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></> : <Navigate to="/login" replace />;
const App = () => { const [user, setUser] = useState<User | null | undefined>(undefined); useEffect(() => onAuthStateChanged(auth, setUser), []); if (user === undefined) return <Loading />; return <Box><Routes><Route path="/login" element={user ? <Navigate to="/dashboard" replace /> : <Login />} /><Route path="/*" element={<Protected user={user} />} /></Routes></Box>; };
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={queryClient}><BrowserRouter><CssBaseline /><App /></BrowserRouter></QueryClientProvider>);

