import { z } from 'zod';
const optionalSecret = z.string().min(1).optional();
export const backendEnvSchema = z.object({ NODE_ENV: z.enum(['development', 'test', 'production']).default('development'), PORT: z.coerce.number().int().positive().default(2301), DEFAULT_TIMEZONE: z.string().default('Europe/Kyiv'), TELEGRAM_BOT_TOKEN: optionalSecret, TELEGRAM_WEBHOOK_SECRET: optionalSecret, TELEGRAM_ALLOWED_USERNAME: z.string().regex(/^[A-Za-z0-9_]{5,32}$/).optional(), OPENAI_API_KEY: optionalSecret, OPENAI_MODEL: z.string().default('gpt-4o-mini'), GOOGLE_CLIENT_ID: optionalSecret, GOOGLE_CLIENT_SECRET: optionalSecret, GOOGLE_REFRESH_TOKEN: optionalSecret, GOOGLE_CALENDAR_ID: optionalSecret, FIREBASE_PROJECT_ID: optionalSecret, ADMIN_UIDS: z.string().default('') });
export type BackendEnv = z.infer<typeof backendEnvSchema>;
export const loadBackendEnv = (source: Record<string, string | undefined>): BackendEnv => backendEnvSchema.parse(source);
export const backendRuntimeEnvSchema = backendEnvSchema.omit({ PORT: true });
export type BackendRuntimeEnv = z.infer<typeof backendRuntimeEnvSchema>;
export const loadBackendRuntimeEnv = (source: Record<string, string | undefined>): BackendRuntimeEnv => backendRuntimeEnvSchema.parse(source);
export const frontendEnvSchema = z.object({ VITE_FIREBASE_API_KEY: z.string().optional(), VITE_FIREBASE_AUTH_DOMAIN: z.string().optional(), VITE_FIREBASE_PROJECT_ID: z.string().optional(), VITE_FIREBASE_APP_ID: z.string().optional() });
export type FrontendEnv = z.infer<typeof frontendEnvSchema>;
