import { GoogleCalendarController } from './google-calendar.controller.js';
import { GoogleCalendarConnection } from './google-calendar.connection.js';
import { GoogleCalendarStore } from './google-calendar.store.js';
import { AiChatController } from './ai-chat.controller.js';
import { AiChatStore } from './ai-chat.store.js';
import { AiChatService } from './ai-chat.service.js';
import { TelegramMcpService } from './telegram-mcp.service.js';
import { MediaStoreController } from './media-store.controller.js';
import { MediaStoreService } from './media-store.service.js';
import { TelegramAccountController } from './telegram-account.controller.js';
import { TelegramAccountService } from './telegram-account.service.js';
import { TelegramAccountStore } from './telegram-account.store.js';
import { TelegramAccountTransport } from './telegram-account.transport.js';
import { TelegramScheduleImportController } from './telegram-schedule-import.controller.js';
import { TelegramScheduleImportService } from './telegram-schedule-import.service.js';
import { TelegramScheduleImportStore } from './telegram-schedule-import.store.js';
import { OpenAiService } from './openai.service.js';
import { Module } from '@nestjs/common';
import { AssistantToolsService } from './assistant-tools.service.js'; import { AdminAuthService, AdminGuard, AdminOwnerGuard } from './auth.js'; import { AvailabilityService } from './availability.service.js'; import { BookingService } from './booking.service.js'; import { CalendarService } from './calendar.js'; import { AdminController, HealthController, TelegramController } from './controllers.js'; import { FirebaseAdminService } from './firebase-admin.js'; import { BookingRepository } from './repository.js'; import { ServicePhotoService } from './service-photo.service.js'; import { SpecService } from './spec.service.js'; import { TelegramService } from './telegram.service.js';
import { HumanAssistanceStore } from './human-assistance.store.js';
import { HumanAssistanceService } from './human-assistance.service.js';
@Module({ controllers: [GoogleCalendarController, AiChatController, MediaStoreController, TelegramAccountController, TelegramScheduleImportController, HealthController, TelegramController, AdminController], providers: [GoogleCalendarConnection, GoogleCalendarStore, AiChatStore, AiChatService, TelegramMcpService, MediaStoreService, TelegramAccountService, TelegramAccountStore, TelegramAccountTransport, TelegramScheduleImportService, TelegramScheduleImportStore, OpenAiService, FirebaseAdminService, AdminAuthService, AdminGuard, AdminOwnerGuard, BookingRepository, CalendarService, BookingService, AvailabilityService, TelegramService, AssistantToolsService, ServicePhotoService, SpecService, HumanAssistanceStore, HumanAssistanceService] }) export class AppModule {}
