import { Injectable } from '@nestjs/common';
import type { CreateBookingRequest, RescheduleBookingRequest } from '@booking/contracts';
import { BookingNotFoundError, ServiceNotFoundError, lockedSlotKeys, serviceEndAt } from '@booking/domain';
import { CalendarService } from './calendar.js'; import { BookingRepository } from './repository.js';
@Injectable()
export class BookingService {
  constructor(private readonly repository: BookingRepository, private readonly calendar: CalendarService) {}
  async create(input: CreateBookingRequest) { const service = await this.repository.getService(input.serviceId); if (!service || !service.enabled) throw new ServiceNotFoundError(); const endAt = serviceEndAt(input.startAt, service); const booking = await this.repository.createBooking({ ...input, endAt, status: 'confirmed', calendarSyncStatus: 'pending', lockedSlots: lockedSlotKeys('default', input.startAt, endAt, service.bufferMinutes), bufferMinutes: service.bufferMinutes }); await this.syncCreated(booking.id); return (await this.repository.getBooking(booking.id))!; }
  async syncCreated(id: string): Promise<void> { const booking = await this.repository.getBooking(id); if (!booking || !this.calendar.isConfigured()) return; try { const eventId = await this.calendar.createBookingEvent(booking); await this.repository.setCalendarSync(id, 'synced', eventId); } catch { await this.repository.setCalendarSync(id, 'failed'); } }
  async cancel(id: string) { const booking = await this.repository.cancelBooking(id); if (booking.googleCalendarEventId) { try { await this.calendar.deleteBookingEvent(booking.googleCalendarEventId); } catch { await this.repository.setCalendarSync(id, 'failed'); } } return booking; }
  async reschedule(id: string, input: RescheduleBookingRequest) { const booking = await this.repository.getBooking(id); if (!booking) throw new BookingNotFoundError(); const service = await this.repository.getService(booking.serviceId); if (!service) throw new ServiceNotFoundError(); const endAt = serviceEndAt(input.startAt, service); const changed = await this.repository.rescheduleBooking(id, input.startAt, endAt, lockedSlotKeys('default', input.startAt, endAt, service.bufferMinutes)); if (this.calendar.isConfigured()) { try { await this.calendar.updateBookingEvent(changed); await this.repository.setCalendarSync(id, 'synced'); } catch { await this.repository.setCalendarSync(id, 'failed'); } } return (await this.repository.getBooking(id))!; }
}
