import { Body, Controller, Delete, Get, Headers, HttpCode, NotFoundException, Param, Patch, Post, Put, Req, UseGuards } from '@nestjs/common';
import { adminAccessResponseSchema, assistantPromptResponseSchema, availabilityRuleSchema, availableSlotsRequestSchema, botSettingsResponseSchema, createBookingRequestSchema, patchConversationSchema, rescheduleBookingRequestSchema, scheduleExceptionSchema, servicePhotoUploadSchema, serviceSchema, updateAdminAccessSchema, updateAssistantPromptSchema, updateBotSettingsSchema, knowledgeBaseResponseSchema, updateKnowledgeBaseSchema, updateBookingRequestSchema, humanAssistanceSettingsResponseSchema, humanReplySchema, updateHumanAssistanceSettingsSchema } from '@booking/contracts';
import { AdminGuard, AdminOwnerGuard, type AdminRequest } from './auth.js'; import { AvailabilityService } from './availability.service.js'; import { BookingService } from './booking.service.js'; import { BookingRepository } from './repository.js'; import { SpecService } from './spec.service.js'; import { TelegramService } from './telegram.service.js'; import { ASSISTANT_SYSTEM_PROMPT } from './assistant-prompt.js';
import { DEFAULT_BOT_SETTINGS } from './bot-settings.js';
import { DEFAULT_KNOWLEDGE_BASE } from './default-knowledge-base.js';
import { ServicePhotoService } from './service-photo.service.js';
import { HumanAssistanceService } from './human-assistance.service.js';
@Controller()
export class HealthController { @Get('health') health() { return { status: 'ok' }; } }
@Controller('telegram')
export class TelegramController { constructor(private readonly telegram: TelegramService) {} @Post('webhook') @HttpCode(200) async webhook(@Headers('x-telegram-bot-api-secret-token') secret: string | undefined, @Body() body: unknown) { await this.telegram.handle(secret, body); return { ok: true }; } }
@UseGuards(AdminGuard) @Controller('admin')
export class AdminController {
  constructor(private readonly repository: BookingRepository, private readonly bookings: BookingService, private readonly availability: AvailabilityService, private readonly specService: SpecService, private readonly servicePhotos: ServicePhotoService, private readonly human: HumanAssistanceService) {}
  @Get('spec') spec() { return this.specService.getSpec(); }
  @Get('assistant-prompt') async assistantPrompt() { return this.promptResponse(await this.repository.getAssistantPromptOverride()); }
  @Put('assistant-prompt') async updateAssistantPrompt(@Body() body: unknown) { const { prompt } = updateAssistantPromptSchema.parse(body); return this.promptResponse(await this.repository.saveAssistantPromptOverride(prompt)); }
  @Delete('assistant-prompt') async resetAssistantPrompt() { await this.repository.deleteAssistantPromptOverride(); return this.promptResponse(); }
  @Get('knowledge-base') async knowledgeBase() { const [override, services] = await Promise.all([this.repository.getKnowledgeBaseOverride(), this.repository.listServices()]); return this.knowledgeBaseResponse(override, services.filter((service) => service.enabled)); }
  @Put('knowledge-base') async updateKnowledgeBase(@Body() body: unknown) { const { content } = updateKnowledgeBaseSchema.parse(body); const [override, services] = await Promise.all([this.repository.saveKnowledgeBaseOverride(content), this.repository.listServices()]); return this.knowledgeBaseResponse(override, services.filter((service) => service.enabled)); }
  @Delete('knowledge-base') async resetKnowledgeBase() { await this.repository.deleteKnowledgeBaseOverride(); return this.knowledgeBaseResponse(undefined, (await this.repository.listServices()).filter((service) => service.enabled)); }
  @Get('bot-settings') async botSettings() { return this.botSettingsResponse(await this.repository.getBotSettingsOverride()); }
  @Put('bot-settings') async updateBotSettings(@Body() body: unknown) { const settings = updateBotSettingsSchema.parse(body); return this.botSettingsResponse(await this.repository.saveBotSettingsOverride(settings)); }
  @Get('human-assistance-settings') async humanAssistanceSettings() { return humanAssistanceSettingsResponseSchema.parse(await this.human.settingsView()); }
  @Put('human-assistance-settings') async updateHumanAssistanceSettings(@Body() body: unknown) { await this.human.saveSettings(updateHumanAssistanceSettingsSchema.parse(body)); return this.humanAssistanceSettings(); }
  @Get('human-requests') humanRequests() { return this.human.listOpen(); }
  @Post('human-requests/:id/reply') replyHumanRequest(@Param('id') id: string, @Body() body: unknown, @Req() request: AdminRequest) { return this.human.reply(id, humanReplySchema.parse(body).text, `admin:${request.admin!.uid}`); }
  @Post('human-requests/:id/release') releaseHumanRequest(@Param('id') id: string, @Req() request: AdminRequest) { return this.human.release(id, `admin:${request.admin!.uid}`); }
  @Get('admin-access') async adminAccess(@Req() request: AdminRequest) { const override = await this.repository.getAdminAccessOverride(); return adminAccessResponseSchema.parse({ emails: override?.emails ?? [], canManage: request.admin?.isOwner ?? false, ...(override?.updatedAt ? { updatedAt: override.updatedAt } : {}) }); }
  @Put('admin-access') @UseGuards(AdminOwnerGuard) async updateAdminAccess(@Body() body: unknown) { const { emails } = updateAdminAccessSchema.parse(body); const saved = await this.repository.saveAdminAccessOverride(emails); return adminAccessResponseSchema.parse({ ...saved, canManage: true }); }
  @Get('dashboard') async dashboard() { const [all, conversations] = await Promise.all([this.repository.listBookings(), this.repository.listConversations()]); const now = new Date(); const today = now.toISOString().slice(0, 10); const weekEnd = new Date(now); weekEnd.setDate(now.getDate() + 7); return { bookingsToday: all.filter((booking) => booking.startAt.startsWith(today)).length, bookingsThisWeek: all.filter((booking) => new Date(booking.startAt) >= now && new Date(booking.startAt) <= weekEnd).length, upcomingBookings: all.filter((booking) => new Date(booking.startAt) >= now), assistantEnabled: conversations.every((conversation) => conversation.assistantEnabled), calendarSyncFailures: all.filter((booking) => booking.calendarSyncStatus === 'failed').length }; }
  @Get('bookings') listBookings() { return this.repository.listBookings(); }
  @Get('bookings/:id') booking(@Param('id') id: string) { return this.repository.getBooking(id); }
  @Post('bookings') createBooking(@Body() body: unknown) { return this.bookings.create(createBookingRequestSchema.parse(body)); }
  @Patch('bookings/:id') patchBooking(@Param('id') id: string, @Body() body: unknown) { const patch = updateBookingRequestSchema.parse(body); return patch.status ? this.repository.updateBookingStatus(id, patch.status) : this.repository.getBooking(id); }
  @Post('bookings/:id/cancel') cancel(@Param('id') id: string) { return this.bookings.cancel(id); }
  @Post('bookings/:id/reschedule') reschedule(@Param('id') id: string, @Body() body: unknown) { return this.bookings.reschedule(id, rescheduleBookingRequestSchema.parse(body)); }
  @Get('services') services() { return this.repository.listServices(); }
  @Post('services') createService(@Body() body: unknown) { return this.repository.saveService(serviceSchema.parse(body)); }
  @Patch('services/:id') async patchService(@Param('id') id: string, @Body() body: unknown) { const current = await this.repository.getService(id); const service = serviceSchema.parse({ ...(body as object), id }); const saved = await this.repository.saveService(service); if (current?.photoUrl && current.photoUrl !== saved.photoUrl) await this.servicePhotos.delete(current.photoUrl); return saved; }
  @Post('services/:id/photo') async uploadServicePhoto(@Param('id') id: string, @Body() body: unknown) { const current = await this.repository.getService(id); if (!current) throw new NotFoundException('Service not found'); const { contentType, base64 } = servicePhotoUploadSchema.parse(body); const photoUrl = await this.servicePhotos.upload(id, { contentType, base64 }); try { await this.repository.saveService({ ...current, photoUrl }); } catch (error) { await this.servicePhotos.delete(photoUrl); throw error; } if (current.photoUrl) await this.servicePhotos.delete(current.photoUrl); return { photoUrl }; }
  @Get('schedule') schedule() { return this.repository.getRules(); }
  @Put('schedule') async putSchedule(@Body() body: unknown) { const rules = availabilityRuleSchema.array().parse(body); await this.repository.setRules(rules); return rules; }
  @Get('schedule-exceptions') exceptions() { return this.repository.getExceptions(); }
  @Post('schedule-exceptions') createException(@Body() body: unknown) { return this.repository.saveException(scheduleExceptionSchema.parse(body)); }
  @Patch('schedule-exceptions/:id') patchException(@Param('id') id: string, @Body() body: unknown) { return this.repository.saveException(scheduleExceptionSchema.parse({ ...(body as object), id })); }
  @Delete('schedule-exceptions/:id') async deleteException(@Param('id') id: string) { await this.repository.deleteException(id); return { ok: true }; }
  @Get('conversations') conversations() { return this.repository.listConversations(); }
  @Patch('conversations/:id') async patchConversation(@Param('id') id: string, @Body() body: unknown) { const changes = patchConversationSchema.parse(body); const existing = await this.repository.getConversation(id); const now = new Date().toISOString(); return this.repository.saveConversation({ ...(existing ?? { telegramChatId: id, assistantEnabled: true, state: 'active', summary: '', createdAt: now }), ...changes, humanTakeoverUntil: changes.humanTakeoverUntil === null ? undefined : changes.humanTakeoverUntil ?? existing?.humanTakeoverUntil, updatedAt: now }); }
  @Post('available-slots') availableSlots(@Body() body: unknown) { return this.availability.find(availableSlotsRequestSchema.parse(body)); }
  private knowledgeBaseResponse(override?: { content: string; updatedAt: string }, services: Awaited<ReturnType<BookingRepository['listServices']>> = []) { return knowledgeBaseResponseSchema.parse({ ...(override ? { ...override, isCustom: true } : { content: DEFAULT_KNOWLEDGE_BASE, isCustom: false }), services: services.map(({ id, name, description, durationMinutes, durationOptions, price, currency }) => ({ id, name, description, durationMinutes, ...(durationOptions ? { durationOptions } : {}), price, currency })) }); }
  private promptResponse(override?: { prompt: string; updatedAt: string }) { return assistantPromptResponseSchema.parse(override ? { ...override, isCustom: true } : { prompt: ASSISTANT_SYSTEM_PROMPT, isCustom: false }); }
  private botSettingsResponse(override?: { maxReadDelayMs: number; typingDelayPerSymbolMs: number; updatedAt: string }) { return botSettingsResponseSchema.parse(override ? { ...override, isCustom: true } : { ...DEFAULT_BOT_SETTINGS, isCustom: false }); }
}
